shares = [
    'MARINETRAN-SM', 'UNICHEMLAB', 'CUB', 'INM-SM', 'VILINBIO-SM', 'TALBROAUTO', 'FIDEL-SM', 'KRISHIVAL-SM', 'GSMFOILS-ST', 'RELTD-BE', 'ABMINTLLTD', 'TECHERA-SM', 'MANAKCOAT-BE', 'MEGASOFT-BE', 'EPACK-BE', 'AMBEY-SM', 'PULZ-ST', 'CROWN-BE', 'VERTEXPLUS-SM', 'RMDRIP-ST', 'TARIL-BE', 'CPS-ST', 'ICDSLTD', 'ONEPOINT', 'KSOLVES', 'INNOVANA-SM', 'LAOPALA', 'PPSL-SM', 'STEELCITY', 'COMSYN', 'PRECOT', 'HINDZINC', 'TIINDIA', 'WEL', 'KRISHANA'
]
