shares = [
    'MARINETRAN-SM', 'SAURASHCEM', 'CUB', 'TALBROAUTO', 'VILINBIO-SM', 'STEELCITY', 'KRISHIVAL-SM', 'EPACK-BE', 'RELTD-BE', 'ABMINTLLTD', 'TECHERA-SM', 'MEGASOFT-BE', 'TIRUPATIFL-BE', 'KICL', 'POLYMED', 'ICDSLTD', 'LAWSIKHO-SM', 'PULZ-ST', 'ARVEE', 'EMMBI', 'CROWN-BE', 'ALBERTDAVD-BE'
]
